"""
Workflow execution engine (Phase 1 simulator).

Runs an agent's workflow task-by-task, records every step in the
execution_steps table, applies retries / fallbacks per task config,
and tallies tokens, cost and latency into the executions table.

The model_call and call_endpoint task types are stubbed so the platform
runs end-to-end without real LLM keys or live integrations. Replace
`_simulate_model_call` and `_simulate_endpoint_call` with real adapters
to go to production.
"""
from __future__ import annotations

import json
import random
import re
import time
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy.orm import Session

from . import models


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_VAR_PATTERN = re.compile(r"\{\{\s*([\w\.]+)\s*\}\}")


def _resolve_template(text: str, context: dict[str, Any]) -> str:
    """Replace {{ var.path }} placeholders using values from context."""
    if not text:
        return text

    def lookup(match: re.Match) -> str:
        path = match.group(1).split(".")
        value: Any = context
        for part in path:
            if isinstance(value, dict) and part in value:
                value = value[part]
            else:
                return match.group(0)  # leave unresolved
        return str(value)

    return _VAR_PATTERN.sub(lookup, text)


def _mask_sensitive(payload: dict, sensitive: list[str]) -> dict:
    """Return a shallow copy with sensitive keys masked for logs."""
    if not payload or not sensitive:
        return payload
    masked = dict(payload)
    for key in sensitive:
        if key in masked:
            masked[key] = "***MASKED***"
    return masked


# ---------------------------------------------------------------------------
# Simulators (replace with real adapters in production)
# ---------------------------------------------------------------------------

def _simulate_endpoint_call(
    endpoint: models.Endpoint, context: dict
) -> tuple[dict, int, float]:
    """Simulate hitting a registered endpoint. Returns (response, latency_ms, cost)."""
    latency = random.randint(80, 400)
    time.sleep(latency / 5000.0)  # short pause for realism, not full latency

    # 95% success rate by default — flip for unstable endpoints
    if random.random() < 0.05:
        raise RuntimeError(f"Endpoint {endpoint.name} returned HTTP 503")

    response = {
        "status": "ok",
        "endpoint": endpoint.name,
        "method": endpoint.method,
        "url": f"{endpoint.base_url}{endpoint.path}",
        "echo_input": context.get("input", {}),
        "data": {
            "id": str(uuid.uuid4())[:8],
            "value": round(random.uniform(10, 1000), 2),
            "timestamp": datetime.utcnow().isoformat(),
        },
    }
    return response, latency, endpoint.estimated_cost_per_call or 0.0


def _simulate_model_call(
    model: models.AIModel, prompt: str, context: dict
) -> tuple[str, int, int, int, float]:
    """Simulate an LLM call. Returns (text, tokens_in, tokens_out, latency_ms, cost)."""
    latency = random.randint(300, 1500)
    time.sleep(latency / 5000.0)

    tokens_in = max(50, len(prompt) // 4)
    tokens_out = random.randint(80, 400)
    cost = (
        (tokens_in / 1000) * (model.cost_per_1k_input_tokens or 0)
        + (tokens_out / 1000) * (model.cost_per_1k_output_tokens or 0)
    )

    text = json.dumps(
        {
            "answer": f"Simulated response from {model.name}",
            "confidence": round(random.uniform(0.7, 0.99), 2),
            "evidence": [
                f"Endpoint data observed in context: {bool(context)}",
                "Generated by execution simulator",
            ],
            "next_actions": ["review", "approve"],
        },
        indent=2,
    )
    return text, tokens_in, tokens_out, latency, cost


# ---------------------------------------------------------------------------
# Step executors per task type
# ---------------------------------------------------------------------------

def _run_task(
    task: models.Task, context: dict, db: Session
) -> dict[str, Any]:
    """Run one task and return its result block (status, output, metrics)."""
    started = datetime.utcnow()
    t0 = time.time()
    result: dict[str, Any] = {
        "status": "success",
        "output": {},
        "tokens_input": 0,
        "tokens_output": 0,
        "cost": 0.0,
        "error": None,
    }

    try:
        if task.task_type == "classify":
            categories = task.config.get("categories", ["general", "billing", "support"])
            result["output"] = {
                "intent": random.choice(categories),
                "confidence": round(random.uniform(0.7, 0.99), 2),
            }

        elif task.task_type in ("retrieve", "call_endpoint"):
            if not task.endpoint_id:
                raise ValueError(f"Task '{task.name}' has no endpoint configured")
            endpoint = db.get(models.Endpoint, task.endpoint_id)
            if endpoint is None:
                raise ValueError(f"Endpoint id={task.endpoint_id} not found")
            response, latency, cost = _simulate_endpoint_call(endpoint, context)
            result["output"] = response
            result["cost"] = cost
            # Apply response mapping into context
            for var_name, mapping in (endpoint.response_mapping or {}).items():
                json_path = mapping.get("json_path") if isinstance(mapping, dict) else mapping
                if json_path:
                    parts = json_path.split(".")
                    value: Any = response
                    for part in parts:
                        if isinstance(value, dict):
                            value = value.get(part)
                        else:
                            value = None
                            break
                    if value is not None:
                        context.setdefault("variables", {})[var_name] = value

        elif task.task_type == "transform":
            mapping = task.config.get("mapping", {})
            transformed = {
                k: _resolve_template(str(v), context) for k, v in mapping.items()
            }
            result["output"] = transformed
            context.setdefault("variables", {}).update(transformed)

        elif task.task_type in ("call_model", "generate"):
            if not task.model_id:
                raise ValueError(f"Task '{task.name}' has no model configured")
            model = db.get(models.AIModel, task.model_id)
            if model is None:
                raise ValueError(f"Model id={task.model_id} not found")
            template = ""
            if task.prompt_id:
                prompt_obj = db.get(models.Prompt, task.prompt_id)
                if prompt_obj is not None:
                    template = prompt_obj.template or ""
            template = template or task.config.get("prompt", "Generate a response.")
            rendered = _resolve_template(template, context)

            text, ti, to, latency, cost = _simulate_model_call(model, rendered, context)
            result["output"] = {"text": text, "model": model.name}
            result["tokens_input"] = ti
            result["tokens_output"] = to
            result["cost"] = cost

        elif task.task_type == "validate":
            schema_keys = task.config.get("required_keys", [])
            target = context.get("last_output", {})
            missing = [k for k in schema_keys if k not in (target if isinstance(target, dict) else {})]
            if missing:
                if task.error_handling == "fail":
                    raise ValueError(f"Schema validation failed, missing: {missing}")
                result["output"] = {"valid": False, "missing": missing}
            else:
                result["output"] = {"valid": True}

        elif task.task_type == "escalate":
            result["output"] = {"escalated": True, "reason": task.config.get("reason", "manual_review")}

        elif task.task_type == "approval":
            # Placeholder — real impl would pause execution and queue approval.
            result["output"] = {"approval": "auto_approved_in_simulator"}

        else:
            # Unknown / loop / future types — succeed with passthrough
            result["output"] = {"note": f"Task type '{task.task_type}' executed (passthrough)"}

    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)

    completed = datetime.utcnow()
    latency_ms = int((time.time() - t0) * 1000)

    step = models.ExecutionStep(
        execution_id=context["execution_id"],
        task_id=task.id,
        step_name=task.name,
        step_type=task.task_type,
        status=result["status"],
        input_data=_mask_sensitive(
            context.get("variables", {}),
            task.config.get("sensitive_fields", []),
        ),
        output_data=result["output"],
        started_at=started,
        completed_at=completed,
        latency_ms=latency_ms,
        cost=result["cost"],
        tokens_input=result["tokens_input"],
        tokens_output=result["tokens_output"],
        error_message=result["error"],
    )
    db.add(step)
    db.flush()

    # Update last_output in shared context for downstream tasks
    context["last_output"] = result["output"]
    return result


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def execute_agent(
    db: Session,
    agent: models.Agent,
    input_data: dict,
    user_id: int | None = None,
) -> models.Execution:
    """Execute the published workflow of an agent and return the Execution row."""
    workflow = (
        db.query(models.Workflow)
        .filter(models.Workflow.agent_id == agent.id)
        .order_by(models.Workflow.version.desc())
        .first()
    )

    correlation_id = str(uuid.uuid4())
    execution = models.Execution(
        correlation_id=correlation_id,
        agent_id=agent.id,
        agent_version=agent.current_version,
        workflow_id=workflow.id if workflow else None,
        user_id=user_id,
        input_data=input_data,
        status="running",
        started_at=datetime.utcnow(),
    )
    db.add(execution)
    db.flush()

    context: dict[str, Any] = {
        "execution_id": execution.id,
        "agent_id": agent.id,
        "input": input_data,
        "variables": {},
    }

    total_cost = 0.0
    total_in = 0
    total_out = 0
    final_output: dict[str, Any] = {}
    failed = False
    escalated = False
    error_message: str | None = None
    t_start = time.time()

    if workflow is None or not workflow.tasks:
        # No workflow configured — fall back to a single direct model call
        # using the agent's default model + system prompt.
        model = (
            db.get(models.AIModel, agent.default_model_id)
            if agent.default_model_id
            else db.query(models.AIModel).first()
        )
        if model is None:
            execution.status = "failed"
            execution.error_message = "No workflow and no AI model available"
            execution.completed_at = datetime.utcnow()
            db.commit()
            return execution

        prompt = _resolve_template(agent.system_prompt or "Respond to the user.", context)
        prompt += f"\n\nUser input: {json.dumps(input_data)}"
        text, ti, to, _lat, cost = _simulate_model_call(model, prompt, context)
        total_in, total_out, total_cost = ti, to, cost
        final_output = {"text": text, "model": model.name}

        step = models.ExecutionStep(
            execution_id=execution.id,
            step_name="direct_model_call",
            step_type="call_model",
            status="success",
            input_data={"prompt_preview": prompt[:300]},
            output_data=final_output,
            started_at=datetime.utcnow(),
            completed_at=datetime.utcnow(),
            cost=cost, tokens_input=ti, tokens_output=to,
        )
        db.add(step)
    else:
        for task in workflow.tasks:
            result = _run_task(task, context, db)
            total_cost += result["cost"]
            total_in += result["tokens_input"]
            total_out += result["tokens_output"]
            final_output = result["output"]

            if result["status"] == "failed":
                if task.error_handling == "escalate":
                    escalated = True
                    break
                if task.error_handling in ("fail", "fallback"):
                    failed = True
                    error_message = result["error"]
                    break
                # error_handling == "continue" → keep going

            if task.task_type == "escalate":
                escalated = True
                break

    execution.completed_at = datetime.utcnow()
    execution.total_latency_ms = int((time.time() - t_start) * 1000)
    execution.total_cost = total_cost
    execution.estimated_cost = round(total_cost * random.uniform(0.85, 1.15), 6)
    execution.total_tokens_input = total_in
    execution.total_tokens_output = total_out
    execution.output_data = final_output
    execution.escalated = escalated
    execution.error_message = error_message
    if failed:
        execution.status = "failed"
    elif escalated:
        execution.status = "escalated"
    else:
        execution.status = "success"

    # Cost record(s)
    db.add(
        models.CostRecord(
            execution_id=execution.id,
            agent_id=agent.id,
            record_type="model",
            tokens_input=total_in,
            tokens_output=total_out,
            cost=total_cost,
            environment=agent.environment,
        )
    )

    db.commit()
    db.refresh(execution)
    return execution
